language: node_js

sudo: false
arch:
  - amd64
  - ppc64le
os:
  - linux
  - windows

node_js:
  - "8"
  - "10"
  - "12"

cache: npm

matrix:
  fast_finish: true

after_success: if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then npm run flow; fi
